### ISSUE TITLE
Implement EngineWrapper

### ISSUE THREAD

**Issue by ChicagoDave** [thiloplanz/glulx-typescript#14]
So Angular 2 is stable now (at least in Beta, not Alpha).

I was wondering if we could work on this again and bring it up to date. I've reviewed what we have and I have some questions...

1. Did you ever get the EngineWrapper working? It doesn't look like it.
2. Is the WebWorker really necessary? I always thought we could just have the EngineWrapper run the Engine for each input. As long as the page isn't reloaded, we can maintain state. If the page is reloaded, we'd have to start everything back up, so we'd need some sort of "start from last point" functionality.
3. We should make everything work with the latest version of Node and Angular 2.
4. My goal is to remove as much of the extra code as possible. We should just have the fyrevm files and the mersenne-twister. We should have a different method for loading the game file than _runGameImage.ts, especially if we get EngineWrapper working.

I guess I'm assuming you're even available. It looks like you've been mostly silent on github.

If you're not interested, that's fine. I'll go look for a new guy. Just wondering if you're up for working on this. I have an author with a story and a design and I'm trying to get some of my ideas implemented.

It would also be good to have an e-mail instead of raising an issue on github!

David

**Comment by thiloplanz** [comment]
I'm not 100% sure anymore what the EngineWrapper does (mostly because, yeah, it's been a while). I suppose it is roughly equivalent to what the WebWorker wrapper now does. 

As for the WebWorker being necessary, what it does is move game processing to a background thread.  The engine is quite slow and running it on the main thread would block the browser UI for an unacceptable amount of time. I suppose this is mostly due to performance issues in the implementation rather than a principle problem. Quixe has a neat JIT compiler, is a lot faster and does not need to use a WebWorker, see #8. So, no, if the code ran faster, one could do without the WebWorker.

>  If the page is reloaded, we'd have to start everything back up, so we'd need some sort of "start from last point" functionality.

We do have the "save" and "restore" opcodes working (#3), so that should be doable.

**Comment by ChicagoDave** [comment]
How much work would it be to implement the Quixe-JIT logic in FyreVM?

EngineWrapper was my attempt at creating a state engine to manage FyreVM.
It allowed me (in C#) to treat the VM as a library and just inflate it as
needed. The engine would never continuously run its main loop. So (inflate
engine, load story, restore save-point, send command, grab results,
deflate).

I think these are the two main things I'd like to get your help with, the
results of which would be the ability to:

node fyrevm mystory.ulx mystory.sav --out results.json

OR (in a browser)

import {fyrevm} ...

EngineWrapper wrapper = new fyrevm.engineWrapper();

wrapper.SendCommand(mystory.ulx, mystory.sav, command)

var results = wrapper.Channels;

wrapper.SendCommand(command);

results = wrapper.Channels;

-----

I'd add that I would like to glue the EngineWrapper to the DOM so later I
can do...

document.FyreVM.SendCommand(...)

results = document.FyreVM.ChannelData;

And never need anything but those two lines from the client code.

---

I can put a job up on Upwork if you need that, but an estimate would be
great. Just a reminder that all of this will be public domain and for fun
on my part. This is my hobby.

Dave

**Comment by thiloplanz** [comment]
> node fyrevm mystory.ulx mystory.sav --out results.json

I have added a such a tool to the "example/node/engineWrapper" directory.  The implementation is rather simplistic, it uses the existing EngineWrapper class (the same one the WebWorker uses) and just issues "save" and "restore" commands to modify a savegame file (called a "session").

Run it like 

> node engineWrapper.js someGameImage.ulx sessionName "look around"

(leave off the command for the first time so that you get the initial output)
It updates the "sessionName.session" file with you move you made, and outputs a JSON with the channel data.

----
> The engine would never continuously run its main loop. 

That part is actually the same here. The engine yields execution and returns to its caller when it has finished processing the game command and requires user input. That's not why I put in on a web worker. It's just that executing the single command can already take a few seconds.

**Comment by thiloplanz** [comment]
Note that the simplistic engine wrapper example does not support undo: There are some parts of the machine state that are not preserved in the savegame file, and this includes the undo stack. As a result, when the wrapper restarts the engine to run the next step, there is no undo information about the previous step.
